import type { InputVolumes } from "../types";
import type {
  ComputedMetrics,
  AutoActionAccuracy,
  CarpenterStats,
  OpsBoardChurn,
  H3DryRunSignal,
} from "./schema";
import { isSectionError } from "./schema";
import { renderPlaceholders } from "./placeholders";

export function writeReflectionMarkdown(
  week: string,
  generatedAt: string,
  workerVersion: string,
  inputVolumes: InputVolumes,
  metrics: ComputedMetrics
): string {
  const fm = [
    "---",
    `week_iso: ${week}`,
    `generated_at: ${generatedAt}`,
    `worker_version: ${workerVersion}`,
    "input_volumes:",
    `  auto_actions_files: ${inputVolumes.auto_actions_files}`,
    `  ops_board_commits: ${inputVolumes.ops_board_commits}`,
    `  carpenter_runs: ${inputVolumes.carpenter_runs}`,
    `  hunter_baseline_runs: ${inputVolumes.hunter_baseline_runs}`,
    "---",
  ].join("\n");

  const s1 = renderSection1(metrics.auto_action_accuracy);
  const s2 = renderSection2(metrics.carpenter_stats);
  const s3 = renderSection3(metrics.ops_board_churn);
  const s4 = renderSection4(metrics.h3_dryrun_signal);
  const placeholders = renderPlaceholders(
    isSectionError(metrics.cost_trajectory) ? metrics.cost_trajectory : metrics.cost_trajectory
  );
  const appendix = renderAppendix(inputVolumes, metrics);

  return `${fm}

# Weekly Reflection — ${week}

> Generated by \`thechefos-reflection\` Worker. Substrate-honest snapshot of what the autonomy layer did this week.

${s1}
${s2}
${s3}
${s4}
${placeholders}

${appendix}`;
}

function renderNotables(notable: string[]): string {
  if (notable.length === 0) return "";
  return "\n**Notable:**\n" + notable.map((n) => `- ${n}`).join("\n");
}

function renderSection1(data: ComputedMetrics["auto_action_accuracy"]): string {
  if (isSectionError(data)) {
    return `## 1. Auto-action accuracy\n\n_Error: ${data.error}_\n`;
  }
  const aa = data as AutoActionAccuracy;
  const verdictRows = Object.entries(aa.by_verdict)
    .sort(([, a], [, b]) => b - a)
    .map(([v, n]) => `| ${v} | ${n} | ${aa.total > 0 ? ((n / aa.total) * 100).toFixed(1) : 0}% |`)
    .join("\n");

  const driftNote =
    aa.flagged_drift.length > 0
      ? `\n**Drift verdicts detected:** ${aa.flagged_drift.join(", ")}`
      : "";

  return `## 1. Auto-action accuracy

**Total entries:** ${aa.total}

| Verdict | Count | % of week |
|---------|-------|-----------|
${verdictRows}
${driftNote}${renderNotables(aa.notable)}`;
}

function renderSection2(data: ComputedMetrics["carpenter_stats"]): string {
  if (isSectionError(data)) {
    return `## 2. Carpenter run stats\n\n_Error: ${data.error}_\n`;
  }
  const cs = data as CarpenterStats;
  const exitRows = Object.entries(cs.by_exit_reason)
    .sort(([, a], [, b]) => b - a)
    .map(([r, n]) => `| ${r} | ${n} |`)
    .join("\n");

  const dist = cs.turn_count_distribution;

  return `## 2. Carpenter run stats

**Total runs:** ${cs.total_runs} | **work_commit null rate:** ${(cs.work_commit_null_rate * 100).toFixed(0)}%

| Exit reason | Count |
|-------------|-------|
${exitRows}

**Turn count distribution:** min=${dist.min} p25=${dist.p25} median=${dist.median} p75=${dist.p75} max=${dist.max} (over_max_turns=${dist.over_max_turns_count})

**Cost:** $${cs.cost_summary.total_usd} total, $${cs.cost_summary.avg_per_run} avg/run, ${cs.cost_summary.null_cost_rows} null-cost rows${renderNotables(cs.notable)}`;
}

function renderSection3(data: ComputedMetrics["ops_board_churn"]): string {
  if (isSectionError(data)) {
    return `## 3. OPS-BOARD churn\n\n_Error: ${data.error}_\n`;
  }
  const ob = data as OpsBoardChurn;
  const m = ob.movements;

  return `## 3. OPS-BOARD churn

**Commits touching board:** ${ob.total_commits_touching_board}

| Movement | Count |
|----------|-------|
| urgent_add | ${m.urgent_add} |
| backlog_add | ${m.backlog_add} |
| claim | ${m.claim} |
| complete | ${m.complete} |
| revert | ${m.revert} |
| remove | ${m.remove} |

**Velocity:** ${ob.velocity.completes_per_day} completes/day | avg URGENT aging: ${ob.velocity.urgent_aging} days${renderNotables(ob.notable)}`;
}

function renderSection4(data: ComputedMetrics["h3_dryrun_signal"]): string {
  if (isSectionError(data)) {
    return `## 4. H3 dry-run signal\n\n_Error: ${data.error}_\n`;
  }
  const h3 = data as H3DryRunSignal;
  const v = h3.verdicts;
  const rec =
    h3.pre_flip_recommendation === "flip_safe"
      ? "✅ **flip_safe**"
      : h3.pre_flip_recommendation === "extend_grace"
        ? "⏳ **extend_grace**"
        : "🔍 **investigate**";

  const blockedRows =
    h3.blocked_complete_mds.length > 0
      ? h3.blocked_complete_mds
          .map((b) => `| ${b.source_path} | ${b.verdict} | ${b.audit_commit.slice(0, 40) || "—"} |`)
          .join("\n")
      : "| _(none)_ | | |";

  return `## 4. H3 dry-run signal

**Total COMPLETE.md pushes:** ${h3.total_complete_md_pushes}

| Verdict | Count |
|---------|-------|
| would_apply | ${v.would_apply} |
| would_block_schema | ${v.would_block_schema} |
| would_block_evidence | ${v.would_block_evidence} |
| would_block_push_unverified | ${v.would_block_push_unverified} |

**Blocked COMPLETE.mds:**

| Source path | Verdict | Audit commit |
|-------------|---------|--------------|
${blockedRows}

**Pre-flip recommendation:** ${rec}${renderNotables(h3.notable)}`;
}

function renderAppendix(inputVolumes: InputVolumes, metrics: ComputedMetrics): string {
  const autoCount = isSectionError(metrics.auto_action_accuracy)
    ? 0
    : (metrics.auto_action_accuracy as AutoActionAccuracy).total;
  const carpCount = isSectionError(metrics.carpenter_stats)
    ? 0
    : (metrics.carpenter_stats as CarpenterStats).total_runs;
  const opsCount = isSectionError(metrics.ops_board_churn)
    ? 0
    : (metrics.ops_board_churn as OpsBoardChurn).total_commits_touching_board;
  const h3Count = isSectionError(metrics.h3_dryrun_signal)
    ? 0
    : (metrics.h3_dryrun_signal as H3DryRunSignal).total_complete_md_pushes;

  return `## Appendix — raw inputs

<details>
<summary>Input volumes</summary>

- auto_actions_files: ${inputVolumes.auto_actions_files} (${autoCount} entries parsed)
- ops_board_commits: ${inputVolumes.ops_board_commits} (${opsCount} classified deltas)
- carpenter_runs: ${inputVolumes.carpenter_runs} (${carpCount} rows)
- hunter_baseline_runs: ${inputVolumes.hunter_baseline_runs}
- h3_dryrun_signal: ${h3Count} complete_validator entries

</details>`;
}
